# various meta-data for MIMIC-IV schema
# it's not clear where these should go

const mimic_module = Dict{Symbol, Symbol}(
    :admissions => :hosp,
    :caregiver => :icu,
    :chartevents => :icu,
    :datetimeevents => :icu,
    :d_hcpcs => :hosp,
    :diagnoses_icd => :hosp,
    :d_icd_diagnoses => :hosp,
    :d_icd_procedures => :hosp,
    :d_items => :icu,
    :d_labitems => :hosp,
    :drgcodes => :hosp,
    :emar_detail => :hosp,
    :emar => :hosp,
    :hcpcsevents => :hosp,
    :icustays => :icu,
    :ingredientevents => :icu,
    :inputevents => :icu,
    :labevents => :hosp,
    :microbiologyevents => :hosp,
    :omr => :hosp,
    :outputevents => :icu,
    :patients => :hosp,
    :pharmacy => :hosp,
    :poe_detail => :hosp,
    :poe => :hosp,
    :prescriptions => :hosp,
    :procedureevents => :icu,
    :procedures_icd => :hosp,
    :provider => :hosp,
    :services => :hosp,
    :transfers => :hosp)

const mimic_pk = Dict{Symbol, Vector{Symbol}}(
    :admissions => [:hadm_id],
    :d_hcpcs => [:code],
    :d_icd_diagnoses => [:icd_code, :icd_version],
    :d_icd_procedures => [:icd_code, :icd_version],
    :d_items => [:itemid],
    :d_labitems => [:itemid],
    :datetimeevents => [:stay_id, :itemid, :charttime],
    :diagnoses_icd => [:hadm_id, :seq_num, :icd_code, :icd_version],
    :emar => [:emar_id],
    :hcpcsevents => [:hadm_id, :hcpcs_cd, :seq_num],
    :icustays => [:stay_id],
    :inputevents => [:orderid, :itemid],
    :labevents => [:labevent_id],
    :microbiologyevents => [:microevent_id],
    :outputevents => [:stay_id, :charttime, :itemid],
    :patients => [:subject_id],
    :pharmacy => [:pharmacy_id],
    :poe => [:poe_id],
    :poe_detail => [:poe_id, :field_name],
    :prescriptions => [:pharmacy_id, :drug_type, :drug],
    :procedureevents => [:orderid],
    :procedures_icd => [:hadm_id, :seq_num, :icd_code, :icd_version],
    :services => [:hadm_id, :transfertime, :curr_service],
    :transfers => [:transfer_id],
   )

const mimic_fk = Dict{Symbol, Vector{NTuple{3, Symbol}}}(
    :admissions => [(:subject_id, :patients, :subject_id)],
    :diagnoses_icd => [(:subject_id, :patients, :subject_id),
                       (:hadm_id, :admissions, :hadm_id)],
    :drgcodes => [(:subject_id, :patients, :subject_id),
                  (:hadm_id, :admissions, :hadm_id)],
    :emar_detail => [(:subject_id, :patients, :subject_id),
                     (:emar_id, :emar, :emar_id)],
    :emar => [(:subject_id, :patients, :subject_id),
              (:hadm_id, :admissions, :hadm_id)],
    :hcpcsevents => [(:subject_id, :patients, :subject_id),
                     (:hadm_id, :admissions, :hadm_id),
                     (:hcpcs_cd, :d_hcpcs, :code)],
    :labevents => [(:subject_id, :patients, :subject_id),
                   (:itemid, :d_labitem, :itemid)],
    :microbiologyevents => [(:subject_id, :patients, :subject_id),
                            (:hadm_id, :admissions, :hadm_id)],
    :pharmacy => [(:subject_id, :patients, :subject_id),
                  (:hadm_id, :admissions, :hadm_id)],
    :poe_detail => [(:subject_id, :patients, :subject_id),
                    (:poe_id, :po, :poe_id)],
    :poe => [(:subject_id, :patients, :subject_id),
             (:hadm_id, :admissions, :hadm_id)],
    :prescriptions => [(:subject_id, :patients, :subject_id),
                       (:hadm_id, :admissions, :hadm_id)],
    :procedures_icd => [(:subject_id, :patients, :subject_id),
                        (:hadm_id, :admissions, :hadm_id)],
    :services => [(:subject_id, :patients, :subject_id),
                  (:hadm_id, :admissions, :hadm_id)],
    :transfers => [(:subject_id, :patients, :subject_id)],
    :chartevents => [(:subject_id, :patients, :subject_id),
                     (:hadm_id, :admissions, :hadm_id),
                     (:stay_id, :icustays, :stay_id),
                     (:itemid, :d_items, :itemid)],
    :datetimeevents => [(:subject_id, :patients, :subject_id),
                        (:hadm_id, :admissions, :hadm_id),
                        (:stay_id, :icustays, :stay_id),
                        (:itemid, :d_items, :itemid)],
    :icustays => [(:subject_id, :patients, :subject_id),
                  (:hadm_id, :admissions, :hadm_id)],
    :inputevents => [(:subject_id, :patients, :subject_id),
                     (:hadm_id, :admissions, :hadm_id),
                     (:stay_id, :icustays, :stay_id),
                     (:itemid, :d_items, :itemid)],
    :outputevents => [(:subject_id, :patients, :subject_id),
                      (:hadm_id, :admissions, :hadm_id),
                      (:stay_id, :icustays, :stay_id),
                      (:itemid, :d_items, :itemid)],
    :procedureevents => [(:subject_id, :patients, :subject_id),
                         (:hadm_id, :admissions, :hadm_id),
                         (:stay_id, :icustays, :stay_id),
                         (:itemid, :d_items, :itemid)])
